/* Generated by tools/gen_ray_tables.py — do not edit.
 * Gather table for the fabric ray-cast kernel: for each of
 * GK_ANGLES candidate needle angles, GK_RADII pixel indices
 * along a ray from the image centre.  Angle 0 = 12 o'clock,
 * clockwise positive; index ai <-> -18000 + ai*GK_STEP_CDEG. */
#ifndef RAY_TABLES_H
#define RAY_TABLES_H

#include <stdint.h>

#define GK_IMG_W 64
#define GK_IMG_H 64
#define GK_IMG_N (64 * 64)
#define GK_ANGLES 240
#define GK_RADII 24
#define GK_STEP_CDEG 150

extern const uint16_t gk_ray_idx[GK_ANGLES * GK_RADII];

#endif /* RAY_TABLES_H */
