#!/usr/bin/env python3
"""Generate firmware/fft_tables.{h,c} — const tables for the 1024-point
fixed-point FFT: periodic Hann window (Q15), bit-reversal permutation,
and twiddle factors (Q15, e^{-2*pi*i*j/N}).

The tables are checked in; rerun only if AU_FFT_N changes:
    python3 tools/gen_tables.py
"""

import math
import pathlib

N = 1024
BITS = 10  # log2(N)
OUT = pathlib.Path(__file__).resolve().parent.parent / "firmware"


def q15(x: float) -> int:
    v = int(round(x * 32767))
    return max(-32768, min(32767, v))


def fmt(vals, per_line=12):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(f"{v}" for v in vals[i:i + per_line]) + ",")
    return "\n".join(lines)


# min(i, N-i) makes w[i] == w[N-i] exact by construction (float cos of
# the two angles can round to Q15 values 1 LSB apart otherwise)
hann = [q15(0.5 * (1.0 - math.cos(2.0 * math.pi * min(i, N - i) / N)))
        for i in range(N)]
bitrev = [int(f"{i:0{BITS}b}"[::-1], 2) for i in range(N)]
tw_re = [q15(math.cos(2.0 * math.pi * j / N)) for j in range(N // 2)]
tw_im = [q15(-math.sin(2.0 * math.pi * j / N)) for j in range(N // 2)]

header = f"""/* Generated by tools/gen_tables.py — do not edit by hand. */
#ifndef FFT_TABLES_H
#define FFT_TABLES_H

#include <stdint.h>

#define AU_TABLES_FFT_N {N}

extern const int16_t  AU_HANN_Q15[{N}];   /* periodic Hann, Q15 */
extern const uint16_t AU_BITREV[{N}];     /* {BITS}-bit bit reversal */
extern const int16_t  AU_TW_RE[{N // 2}];  /* cos(2*pi*j/N), Q15 */
extern const int16_t  AU_TW_IM[{N // 2}];  /* -sin(2*pi*j/N), Q15 */

#endif /* FFT_TABLES_H */
"""

source = f"""/* Generated by tools/gen_tables.py — do not edit by hand. */
#include "fft_tables.h"

const int16_t AU_HANN_Q15[{N}] = {{
{fmt(hann)}
}};

const uint16_t AU_BITREV[{N}] = {{
{fmt(bitrev)}
}};

const int16_t AU_TW_RE[{N // 2}] = {{
{fmt(tw_re)}
}};

const int16_t AU_TW_IM[{N // 2}] = {{
{fmt(tw_im)}
}};
"""

(OUT / "fft_tables.h").write_text(header)
(OUT / "fft_tables.c").write_text(source)
print(f"wrote {OUT / 'fft_tables.h'} and {OUT / 'fft_tables.c'}")
