#!/usr/bin/env python3
"""Generate firmware/ray_tables.{h,c} — the const gather table for the
fabric ray-cast kernel.

For each candidate needle angle (GK_ANGLES steps around the full
circle) the table holds GK_RADII pixel indices sampled along a ray
from the image centre outward.  The fabric kernel scores an angle by
summing pixel darkness through these indices (dst[i] = src[table[i]]
gathers are fabric-friendly; see docs/DEVELOPING_ON_E1.md).

Angle convention (the wire contract, everywhere in this project):
  0 deg = 12 o'clock, clockwise positive, range [-180, +180).
  Score index ai corresponds to angle_cdeg = -18000 + ai * GK_STEP_CDEG.

Checked in; rerun only if the geometry constants change:
  python3 tools/gen_ray_tables.py
"""

import math
import os

IMG_W = 64
IMG_H = 64
N_ANGLES = 240          # 1.5 deg = 150 centidegrees per step (exact)
N_RADII = 24
R_MIN_FRAC = 0.18       # skip the needle hub
R_MAX_FRAC = 0.92       # stay inside the ROI circle

STEP_CDEG = 36000 // N_ANGLES
assert STEP_CDEG * N_ANGLES == 36000, "angle step must be exact in centidegrees"

FW = os.path.join(os.path.dirname(__file__), "..", "firmware")


def build():
    cx, cy = IMG_W / 2.0 - 0.5, IMG_H / 2.0 - 0.5
    half = min(IMG_W, IMG_H) / 2.0
    rmin, rmax = half * R_MIN_FRAC, half * R_MAX_FRAC
    idx = []
    for ai in range(N_ANGLES):
        # 0 = up (12 o'clock), clockwise positive; image y grows down
        theta = math.radians(-180.0 + ai * (360.0 / N_ANGLES))
        dx, dy = math.sin(theta), -math.cos(theta)
        for ri in range(N_RADII):
            r = rmin + (rmax - rmin) * ri / (N_RADII - 1)
            x = round(cx + r * dx)
            y = round(cy + r * dy)
            assert 0 <= x < IMG_W and 0 <= y < IMG_H, (ai, ri, x, y)
            idx.append(y * IMG_W + x)
    return idx


def main():
    idx = build()
    with open(os.path.join(FW, "ray_tables.h"), "w") as f:
        f.write(
            "/* Generated by tools/gen_ray_tables.py — do not edit.\n"
            " * Gather table for the fabric ray-cast kernel: for each of\n"
            " * GK_ANGLES candidate needle angles, GK_RADII pixel indices\n"
            " * along a ray from the image centre.  Angle 0 = 12 o'clock,\n"
            " * clockwise positive; index ai <-> -18000 + ai*GK_STEP_CDEG. */\n"
            "#ifndef RAY_TABLES_H\n#define RAY_TABLES_H\n\n"
            "#include <stdint.h>\n\n"
            f"#define GK_IMG_W {IMG_W}\n"
            f"#define GK_IMG_H {IMG_H}\n"
            f"#define GK_IMG_N ({IMG_W} * {IMG_H})\n"
            f"#define GK_ANGLES {N_ANGLES}\n"
            f"#define GK_RADII {N_RADII}\n"
            f"#define GK_STEP_CDEG {STEP_CDEG}\n\n"
            "extern const uint16_t gk_ray_idx[GK_ANGLES * GK_RADII];\n\n"
            "#endif /* RAY_TABLES_H */\n"
        )
    with open(os.path.join(FW, "ray_tables.c"), "w") as f:
        f.write("/* Generated by tools/gen_ray_tables.py — do not edit. */\n")
        f.write('#include "ray_tables.h"\n\n')
        f.write("const uint16_t gk_ray_idx[GK_ANGLES * GK_RADII] = {\n")
        for i in range(0, len(idx), 12):
            f.write("    " + ", ".join(f"{v}" for v in idx[i:i + 12]) + ",\n")
        f.write("};\n")
    print(f"wrote ray_tables.h/.c: {N_ANGLES} angles x {N_RADII} radii "
          f"({len(idx) * 2} bytes)")


if __name__ == "__main__":
    main()
