/* Generated by tools/gen_tables.py — do not edit by hand. */
#ifndef FFT_TABLES_H
#define FFT_TABLES_H

#include <stdint.h>

#define AU_TABLES_FFT_N 1024

extern const int16_t  AU_HANN_Q15[1024];   /* periodic Hann, Q15 */
extern const uint16_t AU_BITREV[1024];     /* 10-bit bit reversal */
extern const int16_t  AU_TW_RE[512];  /* cos(2*pi*j/N), Q15 */
extern const int16_t  AU_TW_IM[512];  /* -sin(2*pi*j/N), Q15 */

#endif /* FFT_TABLES_H */
